# Generated by Django 4.1.2 on 2023-01-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invetory',
            name='Image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
