# Generated by Django 4.1.2 on 2023-01-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_invetory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewInv', models.FileField(blank=True, upload_to='media')),
            ],
        ),
    ]
