# Generated by Django 4.1.2 on 2023-01-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_uploadcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invetory',
            name='Expiry_Date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='invetory',
            name='Last_Used',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
